ALTER TABLE menu_items
ADD COLUMN calories NUMERIC,
ADD COLUMN protein NUMERIC,
ADD COLUMN carbs NUMERIC,
ADD COLUMN fat NUMERIC,
ADD COLUMN fiber NUMERIC,
ADD COLUMN sugar NUMERIC,
ADD COLUMN sodium NUMERIC;